# Generated by Django 4.2.24 on 2025-09-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_module_batch_updated_at_college_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='auto_promote',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='default_label',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='editable',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='start_date',
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('label', models.CharField(default='Year 1', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auto_promote', models.BooleanField(default=True)),
                ('editable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='accounts.batch')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('batch', 'year')},
            },
        ),
    ]
